name: Release Management

on:
  push:
    tags:
      - 'v*'

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: get-tag
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
      - name: Draft release
        id: release-drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.get-tag.outputs.tag }}
          # disable-releaser: ${{ github.ref_type == 'branch' }}
          disable-releaser: false
          disable-autolabeler: true
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}
      id: ${{ steps.release-drafter.outputs.id }}
      upload-url: ${{ steps.release-drafter.outputs.upload_url }}
  # upload_artifact:
  #   needs: draft-release
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout branch
  #       uses: actions/checkout@v1
  #     - name: Set up JDK 1.8
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 1.8
  #     - name: Build artifact
  #       run: |
  #         echo "New version" > release.md
  #         ./gradlew shadowJar
  #     - name: Upload artifact to GitHub release page
  #       uses: actions/upload-release-asset@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         upload_url: ${{ needs.draft-release.outputs.upload-url }}
  #         asset_path: ./target/*.jar
  #         asset_name: ${{ needs.create_release_draft.outputs.tag }}-latest.jar
  #         asset_content_type: application/zip
