name: On PR

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  lint-PR-title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  label-PR:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          disable-releaser: true
          disable-autolabeler: false
  run-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.action != 'edited' }}
    steps:
      - name: Set up environment
        run: echo "Set up environment"
      - name: Build
        run: echo "Build your project"
      - name: Test
        run: echo "Run your test cases"
