name: On PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: echo "Set up environment"
      - name: Build
        run: echo "Build your project"
      - name: Test
        run: echo "Run your test cases"
